### ISSUE TITLE
Support options_ui and incognito sections

### ISSUE THREAD

**Issue by primaryobjects** [brettz9/convert-manifest-format#3]
Thank you for creating this useful utility.

Please consider adding support for the following:

1. Convert `options` to use `options_ui` as [required](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui) by Firefox.

2. Strip out `incognito: "split"` or convert the value to one [supported](https://firefox-source-docs.mozilla.org/toolkit/components/extensions/webextensions/incognito.html) by Firefox (such as "spanning").

Just suggestions, thank you!

**Comment by brettz9** [comment]
Thank you for your kindness and suggestions!

Do you have any record that `options` was previously used? I don't see it listed at https://developer.chrome.com/docs/extensions/reference/manifest

Regarding `incognito: "split"`, I added a prompt in v0.5.0 if the mode was Firefox and it was found. However, I'd rather not insist that finding a value other than "split" is meant to be converted back to "split" when in Chrome mode (nor hassle the user to prompt them for this each time) since the user might just want it to be "spanning" (or whatever) in both browsers.

**Comment by primaryobjects** [comment]
Ah, correction, it was:

`"options_page": "options.html"`

This is valid for manifest v3 in chrome and edge, but [deprecated](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_page) in Firefox to options_ui.

Thank you.

**Comment by brettz9** [comment]
Ah, great, thanks. I've added support for such conversion in v0.6.0. Closing as that should resolve, though feel free to comment further as needed.
